#version 430 core

layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0, rgba32f) uniform image2D inputImage;
layout (binding = 1, rgba32f) uniform image2D normalImage;
layout (binding = 2, rgba32f) uniform image2D outputImage;

void main()
{
    vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    ivec2 texelCoords = ivec2(gl_GlobalInvocationID.xy);
	
    vec3 color = imageLoad(inputImage, texelCoords).rgb;

    imageStore(outputImage, texelCoords, vec4(color, 1.0));
}